### PR TITLE
Fixes several pathfinding bugs and adds logging

### LINKED ISSUE #80: 🐞Moving on top of food powerups causes the editor to hang
As issue title. The game and editor hangs when attempting to move on top of a food powerup.

Reproduction:
1. Move around the level until you find a fish icon
1. Move onto the fish icon
1. Weep as you are forced to force close the editor using the task manager.

### LINKED ISSUE #81: 🐞Intermittent Pathfinding Crash
Pathfinding sporadically crashes for unknown reasons citing a collection in an invalid state.

Reproduction:
1. Load up a game
1. Run around until you crash, or restart if none happens
1. Note the circumstances in which the crash occurred

### PR DESCRIPTION
**Pull request by Zonr0**
* Fixes #80
* Fixes #81
* Fixes a bug in BucketQueue where the iterator was not iterating
through all buckets
* Adds warning log messages in SearchAStar for unusual or undesirable
circumstances
* Refactors some vector.equals comparisons to == as per Unity doc
reccomendation.

### CODE REVIEW

File: Assets/Scripts/AI/SearchAStar.cs [hunk 1]
```diff
@@ -52,9 +54,20 @@ public class SearchAStar {
         openList.Enqueue(startRecord,(int)startRecord.EstimatedTotalCost);
 
         NodeRecord current = null;
+        Assert.raiseExceptions = true;
         while (openList.Count > 0) {
+            Assert.IsFalse(openList.Count > 50000,"OpenList has an insane number of nodes");
             current = openList.Peek();
 
+            if (openList.Count % 1000 == 0) {
```
Comment (connorkuehl) [inline Assets/Scripts/AI/SearchAStar.cs]: Wouldn't it be easier to say `openList.Count >= 1000`? Also, maybe make this literal a constant because it shows up a couple of times later on.

File: Assets/Scripts/AI/SearchAStar.cs [hunk 2]
```diff
@@ -52,9 +54,20 @@ public class SearchAStar {
...
+                UnityEngine.Debug.LogWarning("<i>Pathfinding:</i> There are too many nodes in the open list. >" + openList.Count);
+                //openList.LogContents();
+            }
+            if (closedList.Count > 0 && closedList.Count % 1000 == 0) {
```
Comment (connorkuehl) [inline Assets/Scripts/AI/SearchAStar.cs]: This if statement and debug message has shown up a couple of times, maybe a

```
void WarnIfOverCapacity(BucketQueue<NodeRecord> list) {
        if (list.Count > 0 && list.Count >= 1000) {
              UnityEngine.Debug.LogWarning("<i>Pathfinding:</i> There are too many nodes in the open list. >" + list.Count); 
        }
}
```

is in order.

File: Assets/Scripts/AI/SearchAStar.cs [hunk 3]
```diff
@@ -67,17 +80,20 @@ public class SearchAStar {
...
+                if (_debugMode) {
                     UnityEngine.Debug.DrawLine(con.From, con.Destination, Color.blue,2,false);
                 }
 
                 //If the node is closed, we may have to skip or remove from the closed list
-                if (closedList.Any(conn => conn.Location.Equals(endLoc))) {
+                if (closedList.Any(closedRecord => closedRecord.Location == endLoc)) {
+                    Assert.IsNotNull(closedList,"Closed List should not be null.");
+                    Assert.IsFalse(closedList.Count == 0,"Closed List should not be empty");
+                    //TODO: This line occasionally crashes. Fix it.
```
Comment (connorkuehl) [inline Assets/Scripts/AI/SearchAStar.cs]: If this PR is coming through, which is fine, because we do need a stability patch, we should raise an issue so that this doesn't get swept under the rug and we duplicate our efforts trying to find this.

**Comment by connorkuehl** [comment]
I think this patch certainly solves one of our stability issue cases. My play tests do feel better, and less prone to random hang-ups.

Pathfinding reports too many nodes in the closed list whenever I am on a fish or near a cluster of them; at least that's what I perceive the pattern to be.

File: Assets/Scripts/AI/SearchAStar.cs (hunk 3 above)
Comment (Zonr0) [inline Assets/Scripts/AI/SearchAStar.cs]: The TODO should be removed. This PR fixes the issue.

File: Assets/Scripts/AI/SearchAStar.cs (hunk 2 above)
Comment (Zonr0) [inline Assets/Scripts/AI/SearchAStar.cs]: It only shows up twice and one's for the open list and one's for the closed list. This would be annoying trying to generalize the log message.

File: Assets/Scripts/AI/SearchAStar.cs (hunk 1 above)
Comment (Zonr0) [inline Assets/Scripts/AI/SearchAStar.cs]: The point of the mod is so that it doesn't spam the console with millions of messages. I wanted it to be evident if it was increasing without bound without filling the log with a million messages.

**Comment by Zonr0** [comment]
I will tweak the maximum distance that the algorithm will travel before giving up, that should hopefully reduce the number of occurrences of the warning and the occasional slowdown when stomping a fish.

File: Assets/Scripts/AI/SearchAStar.cs (hunk 1 above)
Comment (connorkuehl) [inline Assets/Scripts/AI/SearchAStar.cs]: I see, that makes perfect sense!

**Comment by Zonr0** [comment]
Please note that I just pushed a fairly significant update to this PR.

**Comment by Zonr0** [comment]
Addendum: I regret to add that the Fun Police have arrived and have forcibly broken up the conga line.

File: Assets/Scripts/AI/SearchAStar.cs (hunk 2 above)
Comment (peschkaj) [inline Assets/Scripts/AI/SearchAStar.cs]: I'm with Connor. We should remove naked primitives wherever possible, it dramatically improves readability.

```
private static var _tooManyNodes = 1000;
private static var _tooManyNodesMessage = "<i>Pathfinding:</i> There are too many nodes in the {0} list. > {1}";
...
if (list.Count >= _tooManyNodes) {
  UnityEngine.Debug.LogWarning(String.Format(tooManyNodes, "open", list.Count);
}
```

File: Assets/Scripts/AI/SearchAStar.cs [hunk 4]
```diff
@@ -52,32 +55,55 @@ public class SearchAStar {
...
+            Assert.IsFalse(openList.Count > 50000,"OpenList has an insane number of nodes");
             current = openList.Peek();
 
+            if (openList.Count % 1000 == 0) {
+                UnityEngine.Debug.LogWarning("<i>Pathfinding:</i> There are too many nodes in the open list. >" + openList.Count);
+                //openList.LogContents();
+            }
+            if (closedList.Count > 0 && closedList.Count % 1000 == 0) { 
+                UnityEngine.Debug.LogWarning("<i>Pathfinding:</i> There are too many nodes in the closed list. >" + closedList.Count);
+                //closedList.LogContents();
```
Comment (peschkaj) [inline Assets/Scripts/AI/SearchAStar.cs]: Remove these commented lines - if it's not runnable code or an explanation, delete it.

File: Assets/Scripts/Utility/BucketQueue.cs [hunk 5]
```diff
@@ -45,6 +47,17 @@ class BucketQueue<T> : IEnumerable<T> {
             ++Count;
         }
 
+        public void LogContents() {
```
Comment (peschkaj) [inline Assets/Scripts/Utility/BucketQueue.cs]: Make calls to this configurable via some kind of flag. While debugging, I don't need to see a this. Likewise, I'll be adding a combat debug flag later today.

Comment (peschkaj) [inline Assets/Scripts/Utility/BucketQueue.cs]: Or, if you're no longer debugging the BucketQueue, just remove this.
